set(YOCTO_PATH "/mnt/rdk/rdk/build-raspberrypi4-64-rdk-broadband/tmp/work/cortexa72-rdk-linux/opensync/git-r0")
set(YOCTO_SYSROOT ${YOCTO_PATH}/recipe-sysroot)
set(YOCTO_SYSROOT_NATIVE ${YOCTO_PATH}/recipe-sysroot-native)

set(ARCH_PREFIX "aarch64-rdk-linux")
set(TOOLCHAIN_PATH ${YOCTO_SYSROOT_NATIVE}/usr/bin/${ARCH_PREFIX})

set(CMAKE_SYSROOT ${YOCTO_SYSROOT})
set(CMAKE_FIND_ROOT_PATH ${YOCTO_SYSROOT})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PATH}/${ARCH_PREFIX}-g++)
set(CMAKE_C_COMPILER ${TOOLCHAIN_PATH}/${ARCH_PREFIX}-gcc)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
